extends Node


const border_radius_default: StyleBox = preload("res://resource/default_border_radius.tres")
const border_radius_bottom_left: StyleBox = preload("res://resource/bottom_left.tres")
const border_radius_top_left: StyleBox = preload("res://resource/top_left.tres")
const border_radius_top_right: StyleBox = preload("res://resource/top_right.tres")
const border_radius_bottom_right: StyleBox = preload("res://resource/bottom_right.tres")


const default_key_size: Vector2 = Vector2(67, 67)
const up_down_arrow_size: Vector2 = Vector2(67, 30)
const esc_key_size: Vector2 = Vector2(109, 67)
const delete_key_size: Vector2 = Vector2(113, 67)
const tab_key_size: Vector2 = Vector2(113, 67)
const caps_lock_key_size: Vector2 = Vector2(133, 67)
const return_key_size: Vector2 = Vector2(133, 67)
const shift_key_size: Vector2 = Vector2(173, 67)
const space_key_size: Vector2 = Vector2(395, 67)
const command_key_size: Vector2 = Vector2(93, 67)



var is_caps: bool = false

var key_icons: Dictionary = {
	"options": 		"res://assets/icons/apple-keyboard-option.png",
	"brightness2": 	"res://assets/icons/brightness-2.png",
	"brightness": 	"res://assets/icons/brightness.png",
	"command": 		"res://assets/icons/command.png",
	"rewind": 		"res://assets/icons/rewind.png",
	"volume": "res://assets/icons/appple_volume.png",
	"volume_down": 	"res://assets/icons/volume-down.png",
	"volume_up": 	"res://assets/icons/volume-up.png",
	"play": "res://assets/icons/play.png",
	"search": "res://assets/icons/apple_search.png",
	"control": "res://assets/icons/apple_control.png",
	"mic": "res://assets/icons/apple_mic.png",
	"moon": "res://assets/icons/apple_moon.png",
	"fast_forward": "res://assets/icons/apple_fast_forward.png",
	"menu": "res://assets/icons/menu.png"
}

##note:- id:1 <- base_key, id:2 <- shiftable_key, id:3 <- function row key and id:4 <- utility_key
var Key_info_t: Dictionary = {
	"esc": {
		"size": esc_key_size,
		"border_style": border_radius_top_left,
		"key_name": "esc",
		"id": 5,
		"key_id": KEY_ESCAPE,
	},
	"f1": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "F1",
		"id": 3,
		"icon": key_icons.brightness,
		"key_id": KEY_F1,
	},
	"f2": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "F2",
		"id": 3,
		"icon": key_icons.brightness,
		"key_id": KEY_F2,
	},
	"f3": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "F3",
		"id": 3,
		"icon": key_icons.menu,
		"key_id": KEY_F3,
	},
	"f4": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "F4",
		"id": 3,
		"icon": key_icons.search,
		"key_id": KEY_F4,
	},
	"f5": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "F5",
		"id": 3,
		"icon": key_icons.mic,
		"key_id": KEY_F5,
	},
	"f6": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "F6",
		"id": 3,
		"icon": key_icons.moon,
		"key_id": KEY_F6,
	},
	"f7": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "F7",
		"id": 3,
		"icon": key_icons.rewind,
		"key_id": KEY_F7,
	},
	"f8": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "F8",
		"id": 3,
		"icon": key_icons.play,
		"key_id": KEY_F8,
	},
	"f9": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "F9",
		"id": 3,
		"icon": key_icons.fast_forward,
		"key_id": KEY_F9,
	},
	"f10": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "F10",
		"id": 3,
		"icon": key_icons.volume,
		"key_id": KEY_F10,
	},
	"f11": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "F11",
		"id": 3,
		"icon": key_icons.volume_down,
		"key_id": KEY_F11,
	},
	"f12": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "F12",
		"id": 3,
		"icon": key_icons.volume_up,
		"key_id": KEY_F12,
	},
	"lock": {
		"size": default_key_size,
		"border_style": border_radius_top_right,
		"key_name": "",
		"id": 11,
		"icon": key_icons.brightness,
		"key_id": KEY_UNKNOWN,
	},
	"tilde": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "`",
		"id": 2,
		"key_id": KEY_ASCIITILDE,
		"shift_label": "~",
	},
	"1": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "1",
		"id": 2,
		"key_id": KEY_1,
		"shift_label": "!",
	},
	"2": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "2",
		"id": 2,
		"key_id": KEY_2,
		"shift_label": "@",
	},
	"3": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "3",
		"id": 2,
		"key_id": KEY_3,
		"shift_label": "#",
	},
	"4": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "4",
		"id": 2,
		"key_id": KEY_4,
		"shift_label": "$",
	},
	"5": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "5",
		"id": 2,
		"key_id": KEY_5,
		"shift_label": "%",
	},
	"6": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "6",
		"id": 2,
		"key_id": KEY_6,
		"shift_label": "^",
	},
	"7": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "7",
		"id": 2,
		"key_id": KEY_7,
		"shift_label": "&",
	},
	"8": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "8",
		"id": 2,
		"key_id": KEY_8,
		"shift_label": "*",
	},
	"9": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "9",
		"id": 2,
		"key_id": KEY_9,
		"shift_label": "(",
	},
	"0": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "0",
		"id": 2,
		"key_id": KEY_0,
		"shift_label": ")",
	},
	"minus": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "-",
		"id": 2,
		"key_id": KEY_MINUS,
		"shift_label": "_",
	},
	"equal":{
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "=",
		"id": 2,
		"key_id": KEY_EQUAL,
		"shift_label": "+",
	},
	"delete":{
		"size": delete_key_size,
		"border_style": border_radius_default,
		"key_name": "delete",
		"id": 6,
		"key_id": KEY_DELETE,
	},
	"tab":{
		"size": tab_key_size,
		"border_style": border_radius_default,
		"key_name": "tab",
		"id": 5,
		"key_id": KEY_TAB,
	},
	"Q":{
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "Q",
		"id": 1,
		"key_id": KEY_Q,
	},
	"W":{
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "W",
		"id": 1,
		"key_id": KEY_W,
	},
	"E":{
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "E",
		"id": 1,
		"key_id": KEY_E,
	},
	"R":{
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "R",
		"id": 1,
		"key_id": KEY_R,
	},
	"T":{
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "T",
		"id": 1,
		"key_id": KEY_T,
	},
	"Y":{
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "Y",
		"id": 1,
		"key_id": KEY_Y,
	},
	"U":{
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "U",
		"id": 1,
		"key_id": KEY_U,
	},
	"I":{
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "I",
		"id": 1,
		"key_id": KEY_I,
	},
	"O":{
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "O",
		"id": 1,
		"key_id": KEY_O,
	},
	"P":{
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "P",
		"id": 1,
		"key_id": KEY_P,
	},
	"bracket_left": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "[",
		"id": 2,
		"key_id": KEY_BRACKETLEFT,
		"shift_label": "{",
	},
	"bracket_right": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "]",
		"id": 2,
		"key_id": KEY_BRACKETRIGHT,
		"shift_label": "}",
	},
	"forward_slash": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "\\",
		"id": 2,
		"key_id": KEY_SLASH, #forward slash
		"shift_label": "|",
	},
	"caps_lock":{
		"size": caps_lock_key_size,
		"border_style": border_radius_default,
		"key_name": "caps lock",
		"id": 5,
		"key_id": KEY_CAPSLOCK,
	},
	"A":{
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "A",
		"id": 1,
		"key_id": KEY_A,
	},
	"S":{
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "S",
		"id": 1,
		"key_id": KEY_S,
	},
	"D":{
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "D",
		"id": 1,
		"key_id": KEY_D,
	},
	"F":{
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "F",
		"id": 1,
		"key_id": KEY_F,
	},
	"G":{
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "G",
		"id": 1,
		"key_id": KEY_G,
	},
	"H":{
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "H",
		"id": 1,
		"key_id": KEY_H,
	},
	"J":{
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "J",
		"id": 1,
		"key_id": KEY_J,
	},
	"K":{
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "K",
		"id": 1,
		"key_id": KEY_K,
	},
	"L":{
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "L",
		"id": 1,
		"key_id": KEY_L,
	},
	"semi-colon": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": ";",
		"id": 2,
		"key_id": KEY_SEMICOLON,
		"shift_label": ":",
	},
	"apostrophe": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "'",
		"id": 2,
		"key_id": KEY_APOSTROPHE,
		"shift_label": '"',
	},
	"return":{
		"size": return_key_size,
		"border_style": border_radius_default,
		"key_name": "return",
		"id": 6,
		"key_id": KEY_ENTER,
	},
	"l_shift":{
		"size": shift_key_size,
		"border_style": border_radius_default,
		"key_name": "shift",
		"id": 5,
		"key_id": KEY_SHIFT,
	},
	"Z":{
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "z",
		"id": 1,
		"key_id": KEY_Z,
	},
	"X":{
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "X",
		"id": 1,
		"key_id": KEY_X,
	},
	"C":{
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "C",
		"id": 1,
		"key_id": KEY_C,
	},
	"V":{
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "V",
		"id": 1,
		"key_id": KEY_V,
	},
	"B":{
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "B",
		"id": 1,
		"key_id": KEY_B,
	},
	"N":{
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "N",
		"id": 1,
		"key_id": KEY_N,
	},
	"M":{
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "M",
		"id": 1,
		"key_id": KEY_M,
	},
	"comma": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": ",",
		"id": 2,
		"key_id": KEY_COMMA,
		"shift_label": "<",
	},
	"full_stop": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": ".",
		"id": 2,
		"key_id": KEY_STOP,
		"shift_label": ">",
	},
	"backslash": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "/",
		"id": 2,
		"key_id": KEY_BACKSLASH,
		"shift_label": "?",
	},
	"r_shift": {
		"size": shift_key_size,
		"border_style": border_radius_default,
		"key_name": "shift",
		"id": 6,
		"key_id": KEY_SHIFT,
	},
	"fn": {
		"size": default_key_size,
		"border_style": border_radius_bottom_left,
		"key_name": "fn",
		"id": 10,
		"icon": key_icons.brightness,
		"key_id": KEY_UNKNOWN,
	},
	"control": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "control",
		"id": 4,
		"icon": key_icons.control,
		"key_id": KEY_CONTROL,
	},
	"l_option": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "option",
		"id": 4,
		"icon": key_icons.options,
		"key_id": KEY_ALT,
	},
	"l_command": {
		"size": command_key_size,
		"border_style": border_radius_default,
		"key_name": "command",
		"id": 8,
		"icon": key_icons.command,
		"key_id": KEY_META,
	},
	"space":{
		"size": space_key_size,
		"border_style": border_radius_default,
		"key_name": "space",
		"id": 1,
		"key_id": KEY_SPACE,
	},
	"r_command": {
		"size": command_key_size,
		"border_style": border_radius_default,
		"key_name": "command",
		"id": 9,
		"icon": key_icons.command,
		"key_id": KEY_META,
	},
	"r_option": {
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "option",
		"id": 7,
		"icon": key_icons.options,
		"key_id": KEY_ALT,
	},
	#arrow keys here
	"l_arrow":{
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "◀",
		"id": 1,
		"key_id": KEY_LEFT,
	},
	"up_arrow":{
		"size": up_down_arrow_size,
		"border_style": border_radius_default,
		"key_name": "▲",
		"id": 1,
		"key_id": KEY_UP,
	},
	"down_arrow":{
		"size": up_down_arrow_size,
		"border_style": border_radius_default,
		"key_name": "▼",
		"id": 1,
		"key_id": KEY_DOWN,
	},
	"r_arrow":{
		"size": default_key_size,
		"border_style": border_radius_default,
		"key_name": "▶",
		"id": 1,
		"key_id": KEY_RIGHT,
	},
}
